# HQNN Stage 2: Hyperbolic Tensor Network Assembly
# File: Tensor_network_2.py
#
# Depends on: Perfect_tensor_1.py (Stage 1)
# Run Perfect_tensor_1.py first to generate perfect_tensor.npy
# before running this file.
#
# What this file does:
#   1. Loads the perfect tensor saved by Perfect_tensor_1.py
#   2. Builds a small 3-node tensor network graph using networkx
#   3. Assigns perfect tensors to each node
#   4. Contracts tensors along shared (internal) edges using opt_einsum
#   5. Identifies the resulting boundary and bulk (logical) indices
#   6. Verifies the full network encoding map is an isometry
#
# Network structure used here:
#
#        [Node 1]
#           |
#        [Node 0]  <- central tensor
#           |
#        [Node 2]
#
# Node 0 is the central tensor. It connects to Node 1 and Node 2
# via one internal leg each. All remaining legs are either boundary
# physical qubits or bulk logical qubits.
#
# This is the smallest non-trivial holographic network — one step
# above a single perfect tensor. Stage 3 will extend this to a
# proper multi-layer hyperbolic tessellation.

import numpy as np
import networkx as nx
import opt_einsum as oe
from itertools import combinations

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
import os
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# SECTION 1: Load the Perfect Tensor from Perfect_tensor_1.py
#
# The perfect tensor has shape (2,2,2,2,2,2,2,2) — 8 indices total.
# Indices 0-5 are physical qubit legs (can be boundary or internal).
# Indices 6-7 are logical qubit legs (bulk — always uncontracted).
#
# In the network, physical legs either:
#   - Connect to another tensor (internal edge — gets contracted)
#   - Remain free (boundary edge — becomes a physical qubit input/output)
#
# Logical legs always remain free — they are the encoded information.

print("HQNN Stage 2: Hyperbolic Tensor Network Assembly")
print()

print("STEP 1: Loading perfect tensor from Perfect_tensor_1.py")

try:
    T = np.load(os.path.join(SCRIPT_DIR, "perfect_tensor.npy"))
    print(f"  Loaded successfully. Shape: {T.shape}")
    print(f"  Indices 0-5 -> physical legs")
    print(f"  Indices 6-7 -> logical (bulk) legs")
except FileNotFoundError:
    print("  ERROR: perfect_tensor.npy not found.")
    print("  Run Perfect_tensor_1.py first, then re-run this file.")
    print("  Make sure both files are in the same folder:")
    print("    ~/hqnn/Perfect_tensor_1.py")
    print("    ~/hqnn/Tensor_network_2.py")
    print("    ~/hqnn/perfect_tensor.npy  <- generated by Perfect_tensor_1.py")
    exit()

print()

# SECTION 2: Build the Tensor Network Graph
#
# We use networkx to represent the network structure explicitly.
# Each node = one tensor placement.
# Each edge = one contracted index pair between two tensors.
#
# For our 3-node network:
#   Node 0 (central): uses physical index 4 to connect to Node 1
#                     uses physical index 5 to connect to Node 2
#   Node 1 (leaf):    uses physical index 0 to connect to Node 0
#   Node 2 (leaf):    uses physical index 0 to connect to Node 0
#
# The choice of which physical index to use for each connection is
# arbitrary — any physical index can serve as an internal leg.
# We just need to be consistent in the einsum below.

print("STEP 2: Building tensor network graph")

G = nx.Graph()

# add nodes — each node will hold one copy of the perfect tensor
G.add_node(0, role="central")
G.add_node(1, role="leaf")
G.add_node(2, role="leaf")

# add edges — each edge represents a contraction between two tensors
# the edge attributes record which physical index of each tensor is contracted
G.add_edge(0, 1, index_0=4, index_1=0)   # Node 0's index 4 <-> Node 1's index 0
G.add_edge(0, 2, index_0=5, index_1=0)   # Node 0's index 5 <-> Node 2's index 0

print(f"  Nodes: {list(G.nodes(data=True))}")
print(f"  Edges: {list(G.edges(data=True))}")
print(f"  Number of tensors: {G.number_of_nodes()}")
print(f"  Number of internal contractions: {G.number_of_edges()}")
print()

# SECTION 3: Define the Index Assignment Scheme
#
# Before contracting, we need to assign a unique integer label to every
# index of every tensor. Shared indices (contracted edges) get the SAME
# label — opt_einsum uses this to know which indices to sum over.
#
# Labelling scheme:
#   Node 0 (central):  labels  0-7   (8 indices: physical 0-5, logical 6-7)
#   Node 1 (leaf):     labels  8-15  (8 indices: physical 8-13, logical 14-15)
#   Node 2 (leaf):     labels 16-23  (8 indices: physical 16-21, logical 22-23)
#
# Contracted pairs (shared labels):
#   Node 0's physical index 4 (label 4) <-> Node 1's physical index 0 (label 8)
#   -> both get the SAME label: we remap Node 1's index 0 to label 4
#
#   Node 0's physical index 5 (label 5) <-> Node 2's physical index 0 (label 16)
#   -> both get the SAME label: we remap Node 2's index 0 to label 5
#
# Free indices (not contracted) appear in the output.

print("STEP 3: Assigning index labels for opt_einsum")

# Base labels for each tensor (before applying shared index remapping)
# Node 0: indices 0,1,2,3,4,5,6,7
# Node 1: indices 8,9,10,11,12,13,14,15
# Node 2: indices 16,17,18,19,20,21,22,23

node0_indices = [0,  1,  2,  3,  4,  5,  6,  7]
node1_indices = [8,  9, 10, 11, 12, 13, 14, 15]
node2_indices = [16, 17, 18, 19, 20, 21, 22, 23]

# Apply contractions:
# Node 0's physical index 4 (position 4 in node0_indices -> label 4)
# contracts with Node 1's physical index 0 (position 0 in node1_indices)
# -> remap node1_indices[0] to label 4 (same as node0_indices[4])
node1_indices[0] = node0_indices[4]   # label 4 shared

# Node 0's physical index 5 (position 5 in node0_indices -> label 5)
# contracts with Node 2's physical index 0 (position 0 in node2_indices)
# -> remap node2_indices[0] to label 5 (same as node0_indices[5])
node2_indices[0] = node0_indices[5]   # label 5 shared

print(f"  Node 0 indices: {node0_indices}")
print(f"  Node 1 indices: {node1_indices}  (index[0]=4 shared with Node 0)")
print(f"  Node 2 indices: {node2_indices}  (index[0]=5 shared with Node 0)")
print()

# Identify free (output) indices — all labels that are NOT shared
# Shared labels are those appearing in more than one tensor's index list
all_indices = node0_indices + node1_indices + node2_indices
shared = {4, 5}   # the contracted labels

# Output indices = all unique labels that are not contracted
output_indices = [idx for idx in sorted(set(all_indices)) if idx not in shared]

print(f"  Contracted (internal) labels: {sorted(shared)}")
print(f"  Free (output) labels: {output_indices}")
print(f"  Number of free indices: {len(output_indices)}")
print()

# Identify which free indices are boundary (physical) vs bulk (logical)
# Physical legs of Node 0: indices 0,1,2,3 (index 4 and 5 are contracted)
# Physical legs of Node 1: indices 9,10,11,12,13 (index 8 is label 4, contracted)
# Physical legs of Node 2: indices 17,18,19,20,21 (index 16 is label 5, contracted)
# Logical legs: 6,7 (Node 0), 14,15 (Node 1), 22,23 (Node 2)

boundary_labels = [0,  1,  2,  3,         # Node 0 free physical legs
                   9,  10, 11, 12, 13,    # Node 1 free physical legs
                   17, 18, 19, 20, 21]    # Node 2 free physical legs

logical_labels  = [6,  7,                 # Node 0 logical (bulk) legs
                   14, 15,                # Node 1 logical (bulk) legs
                   22, 23]               # Node 2 logical (bulk) legs

print(f"  Boundary (physical) labels: {boundary_labels}  ({len(boundary_labels)} qubits)")
print(f"  Logical (bulk) labels:      {logical_labels}   ({len(logical_labels)} qubits)")
print()

# SECTION 4: Contract the Tensor Network
#
# We use opt_einsum to perform the tensor contraction efficiently.
# The interleaved format passes alternating (tensor, index_list) pairs,
# followed by the desired output index list.
#
# opt_einsum automatically finds the optimal contraction order to
# minimise computational cost — important for larger networks.
#
# The result is a tensor with one index for each free label.
# Its shape will be (2, 2, 2, ...) with one 2 per free index.

print("STEP 4: Contracting the tensor network")

# output order: boundary indices first, then logical indices
# this makes the isometry check cleaner
output_order = boundary_labels + logical_labels

print(f"  Contracting 3 tensors...")
print(f"  Output index order: boundary first, then logical")

network_tensor = oe.contract(
    T, node0_indices,    # central tensor
    T, node1_indices,    # left leaf tensor
    T, node2_indices,    # right leaf tensor
    output_order         # desired output index ordering
)

print(f"  Contraction complete.")
print(f"  Network tensor shape: {network_tensor.shape}")
print(f"  Expected shape: {tuple([2] * len(output_order))}")
print()

# SECTION 5: Reshape for Isometry Verification
#
# The contracted network tensor has shape (2,2,...,2) with:
#   - First 13 indices -> boundary physical qubits
#   - Last  6 indices  -> logical (bulk) qubits
#
# To check the isometry, we reshape into a matrix:
#   rows  -> boundary space:  2^13 = 8192
#   cols  -> logical space:   2^6  = 64
#
# The encoding map E: C^64 -> C^8192 should satisfy E†E = I_64
# meaning: the network perfectly encodes 6 logical qubits into
# 13 physical boundary qubits without any information loss.

print("STEP 5: Reshaping for isometry verification")

n_boundary = len(boundary_labels)
n_logical  = len(logical_labels)

dim_boundary = 2 ** n_boundary
dim_logical  = 2 ** n_logical

print(f"  Boundary qubits: {n_boundary}  ->  dim = 2^{n_boundary} = {dim_boundary}")
print(f"  Logical qubits:  {n_logical}   ->  dim = 2^{n_logical}  = {dim_logical}")
print()

# reshape: (2,...,2) -> (dim_boundary, dim_logical)
E = network_tensor.reshape(dim_boundary, dim_logical)

print(f"  Encoding map E shape: {E.shape}")
print(f"  E maps: C^{dim_logical} (logical) -> C^{dim_boundary} (boundary)")
print()

# SECTION 6: Verify the Network Encoding is an Isometry
#
# A valid holographic encoding must satisfy E†E = I_logical.
# This means:
#   - Orthogonal logical states remain orthogonal after encoding
#   - No information is lost in the encoding process
#   - The encoding can be perfectly inverted via E† on the code subspace
#
# If this passes, the tensor network implements a valid holographic
# encoding map — the core requirement for the HQNN architecture.

print("STEP 6: Verifying network isometry E†E = I")

EtE = E.conj().T @ E   # shape: (dim_logical, dim_logical)

isometry_check = np.allclose(EtE, np.eye(dim_logical), atol=1e-8)

# measure how far from identity (should be ~0 for a valid isometry)
deviation = np.max(np.abs(EtE - np.eye(dim_logical)))

print(f"  E†E = I_{dim_logical} satisfied: {isometry_check}")
print(f"  Max deviation from identity: {deviation:.2e}")
print()

if isometry_check:
    print("  NETWORK ISOMETRY VERIFIED")
    print(f"  The 3-tensor network encodes {n_logical} logical qubits")
    print(f"  into {n_boundary} boundary physical qubits isometrically.")
    print("  Stage 2 complete — ready for Stage 3.")
else:
    print("  ISOMETRY CHECK FAILED")
    print("  The network encoding is not isometric.")
    print("  Check the index assignments and contraction labels above.")

print()

# SECTION 7: Network Structure Summary
#
# Print a summary of the network — which nodes exist, which edges
# connect them, and what each free index represents physically.

print("STEP 7: Network structure summary")
print()
print("  Graph layout:")
print()
print("       [Node 1]  (leaf)")
print("       /")
print("  [Node 0]  (central)")
print("       \\")
print("       [Node 2]  (leaf)")
print()
print("  Internal edges (contracted):")
for u, v, data in G.edges(data=True):
    print(f"    Node {u} [physical index {data['index_0']}]")
    print(f"      <-> Node {v} [physical index {data['index_1']}]")
print()
print("  Free boundary legs (physical qubits):")
print(f"    Node 0: 4 boundary legs  (physical indices 0,1,2,3)")
print(f"    Node 1: 5 boundary legs  (physical indices 1,2,3,4,5)")
print(f"    Node 2: 5 boundary legs  (physical indices 1,2,3,4,5)")
print(f"    Total: {n_boundary} boundary qubits")
print()
print("  Bulk legs (logical qubits):")
print(f"    Node 0: 2 logical legs")
print(f"    Node 1: 2 logical legs")
print(f"    Node 2: 2 logical legs")
print(f"    Total: {n_logical} logical qubits")
print()

# SECTION 8: Save the Network Encoding Map
#
# Save both the full network tensor and the reshaped encoding map E
# for use in Stage 3, where we add the parameterised boundary circuit.

np.save(os.path.join(SCRIPT_DIR, "network_tensor.npy"), network_tensor)
np.save(os.path.join(SCRIPT_DIR, "encoding_map.npy"), E)

print("  Files saved:")
print("  network_tensor.npy  — full tensor, shape (2,...,2)")
print("  encoding_map.npy    — reshaped E matrix, shape")
print(f"                        ({dim_boundary}, {dim_logical})")
print("  Load in Stage 3 with:")
print("    E = np.load('encoding_map.npy')")
